# Generated by Django 5.1.4 on 2024-12-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Enter a unique email address.",
                max_length=254,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="google_calendar_integration",
            field=models.BooleanField(
                default=False,
                help_text="Enable or disable Google Calendar integration.",
                verbose_name="Google Calendar Integration",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light Theme"),
                    ("dark", "Dark Theme"),
                    ("motivating", "Motivating Theme"),
                ],
                default="light",
                help_text="Select a theme for your interface.",
                max_length=20,
                verbose_name="Theme",
            ),
        ),
    ]
