# Generated by Django 5.1.4 on 2025-01-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_customuser_options_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.JSONField(
                default=list,
                help_text="Select the days for this habit.",
                verbose_name="Days of the Week",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.ForeignKey(
                help_text="Select a category for this habit.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to="service.category",
                verbose_name="Category",
            ),
        ),
    ]
