# Generated by Django 5.1.4 on 2025-01-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_category_habit_priority_alter_habit_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("not_completed", "Not Completed"),
                    ("skipped", "Skipped"),
                ],
                default="not_completed",
                max_length=15,
            ),
        ),
    ]
