# Generated by Django 5.1.4 on 2025-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_contribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/img/avatars/default_avatar.png",
                help_text="Upload a profile picture.",
                upload_to="static/img/avatars/",
                verbose_name="Avatar",
            ),
        ),
        migrations.DeleteModel(
            name="Contribution",
        ),
    ]
