# Generated by Django 5.1.4 on 2025-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_customuser_avatar_delete_contribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.png",
                help_text="Upload a profile picture.",
                upload_to="avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
