# Generated by Django 5.1.4 on 2025-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/img/avatars/default_avatar.png",
                help_text="Upload a profile picture.",
                upload_to="media/img/avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
