# Generated by Django 5.1.4 on 2025-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default/default_avatar2.jpg",
                help_text="Upload a profile picture.",
                upload_to="avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
