# Generated by Django 5.1.5 on 2025-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='a', help_text='Upload a profile picture.', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
