# Generated by Django 5.1.4 on 2025-02-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0014_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Enter your bio", verbose_name="Bio"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar.jpg",
                help_text="Upload a profile picture.",
                upload_to="avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
