# Generated by Django 5.1.6 on 2025-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_customuser_bio_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter your bio', max_length=250, verbose_name='Bio'),
        ),
    ]
