# Generated by Django 5.1.8 on 2025-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_schedule_status_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done'), ('missed', 'Missed')], default='not_done', max_length=10, verbose_name='Status'),
        ),
    ]
