# Generated by Django 5.1.8 on 2026-05-01 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_task_options_habit_last_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='earned_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='image_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='key',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
